# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\jupyter_server-feedstock\recipe, last modified Tue Dec  5 16:43:31 2023
# ------------------------------------------------

package:
  name: jupyter_server
  version: 2.10.0
source:
  patches:
    - 00_allow_root_in_tests.patch
  sha256: 47b8f5e63440125cb1bb8957bf12b18453ee5ed9efe42d2f7b2ca66a7019a278
  url: https://pypi.io/packages/source/j/jupyter_server/jupyter_server-2.10.0.tar.gz
build:
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main
  number: '0'
  script: C:\\Users\\dev-admin\\perseverance-python-buildout\\croot\\jupyter_server_1701806473214\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - editables 0.3 py312haa95532_0
    - expat 2.5.0 hd77b12b_0
    - hatch-jupyter-builder 0.8.3 py312haa95532_0
    - hatchling 1.18.0 py312haa95532_1
    - icu 73.1 h6c2663c_0
    - libffi 3.4.4 hd77b12b_0
    - nodejs 18.16.0 haa95532_1
    - openssl 3.0.12 h2bbff1b_0
    - packaging 23.1 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 23.3.1 py312haa95532_0
    - pluggy 1.0.0 py312haa95532_1
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.10.18 py312haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - anyio >=3.1.0
    - argon2-cffi
    - jinja2
    - jupyter_client >=7.4.4
    - jupyter_core >=4.12,!=5.0.*
    - jupyter_events >=0.6.0
    - jupyter_server_terminals
    - nbconvert >=6.4.4
    - nbformat >=5.3.0
    - overrides
    - packaging
    - prometheus_client
    - python >=3.12,<3.13.0a0
    - pywinpty
    - pyzmq >=24
    - send2trash >=1.8.2
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.6.0
    - websocket-client
test:
  commands:
    - pip check
    - jupyter server -h
    - echo "not (test_culling or test_restart_kernel[jp_server_config0] or test_connection[jp_server_config0]
      or test_terminal or test_authorized_requests)"
    - pytest -vvv --cov=jupyter_server -k "not (test_culling or test_restart_kernel[jp_server_config0]
      or test_connection[jp_server_config0] or test_terminal or test_authorized_requests)"
      --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=70
  imports:
    - jupyter_server
  requires:
    - coverage
    - flaky
    - ipykernel
    - pip
    - posix
    - pytest >=7.0
    - pytest-console-scripts
    - pytest-cov
    - pytest-jupyter-server >=0.4
    - pytest-timeout
    - requests
  source_files:
    - tests
about:
  description: The Jupyter Server provides the backend for Jupyter web applications
    such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - Zsailer
    - blink1073
    - bollwyvl
    - jasongrout
    - maartenbreddels
    - minrk
